<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Version>0.0.1</Version>
    <Company>NInferEZ contributors</Company>
    <Product>NInferEZ Manager</Product>
    <Copyright>Copyright (c) 2026 NInferEZ Manager contributors</Copyright>
    <NuGetAudit>false</NuGetAudit>
  </PropertyGroup>
</Project>
