<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>NInferManager.Backend</AssemblyName>
    <RootNamespace>NInferManager.Backend</RootNamespace>
    <Version>0.0.1</Version>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NInferManager.Contracts\NInferManager.Contracts.csproj" />
    <EmbeddedResource Include="Assets\catalog.json" />
  </ItemGroup>
</Project>
